//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiangVien
    {
        public string MGV { get; set; }
        public string GvUser { get; set; }
        public string GvPass { get; set; }
        public string HoTenGV { get; set; }
        public System.DateTime NgaySinhGV { get; set; }
        public bool GioiTinh { get; set; }
        public string MaKhoa { get; set; }
    
        public virtual Khoa Khoa { get; set; }
    }
}
